### ISSUE TITLE
Negative values on 0.12.7

### ISSUE THREAD

**Issue by ghost** [royaltm/node-murmurhash-native#2]
I'm receiving negative hash values for 32 bit hash v3:

```
murmurHash('123');
// It's -1632341525, however should be Math.pow(2,32) - 1632341525 = 2662625771
```

**Comment by royaltm** [comment]
Original implementation of murmurhash doesn't specify how do you interpret those 32 bits of data:
`void MurmurHash3_x86_32 ( const void * key, int len, uint32_t seed, void * out );`
In this package a "number" output (which is default for 32 bit version) is defined as "a 32-bit integer" which is signed integer by default.

If you want unsigned 32-bit integer just convert it with e.g.:

``` js
var hash = murmurHash(input)>>>0;
```

**Comment by royaltm** [comment]
Perhaps for clarity I could just add "uint32" and "int32" explicit output types. What do you think?

**Comment by ghost** [comment]
Ok, let's follow original. Would be nice if you mention that it's signed and the code to make it unsigned.

**Comment by ghost** [comment]
In readme.md

**Comment by royaltm** [comment]
done
