### ISSUE TITLE
Add support for murmurhash64 on the incremental api

### ISSUE THREAD

**Issue by chrisvlopez** [royaltm/node-murmurhash-native#29]
I am getting `Error: Algorithm not supported` when doing `new MurmurHash('murmurhash64')` using `murmurhash-native@3.5.0`

`getHashes()` returns:
```
    [
      'murmurhash',
      'murmurhash128x64',
      'murmurhash128x86',
      'murmurhash128'
    ]
```

Is it possible to add support for `murmurhash64`? I poked around in the C++ [incremental code](https://github.com/royaltm/node-murmurhash-native/blob/master/src/incremental/hasher.cc#L639) but didn't see `murmurhash64` so I suspect this may be a non-trivial ask but hoping I'm wrong!

**Comment by royaltm** [comment]
Unfortunately, it's a non-trivial one. I implemented incremental mm-128 for my own purposes, the original murmurhash only had 32-bit incremental version.

I have neither time nor incentive for doing that with mm-64 but you are welcome to contribute.
